version: '3.7'
services:
  frontend:
    container_name: frontend
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules
      - /usr/src/.next